<?php

namespace Ikerib\IkasiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends EntityRepository
{
  public function checkIfItIsCorrectAnswer($question_id, $answer_id)
  {

    $em = $this->getEntityManager();

    $query = $em->createQuery('
        SELECT a
        FROM IkasiBundle:Answer a
        WHERE a.id = :answer_id
        AND a.question = :question_id
    ');

    $query->setParameter('question_id', $question_id);
    $query->setParameter('answer_id', $answer_id);

    return $query->getResult();

  }
}
