<?php

namespace Ikerib\IkasiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuestoRepository extends EntityRepository
{
}
