puesto:
    path:     /
    defaults: { _controller: "IkasiBundle:Puesto:index" }

admin_puesto_show:
    path:     /{id}/show
    defaults: { _controller: "IkasiBundle:Puesto:show" }

admin_puesto_new:
    path:     /new
    defaults: { _controller: "IkasiBundle:Puesto:new" }

admin_puesto_create:
    path:     /create
    defaults: { _controller: "IkasiBundle:Puesto:create" }
    methods:  POST

admin_puesto_edit:
    path:     /{id}/edit
    defaults: { _controller: "IkasiBundle:Puesto:edit" }

admin_puesto_update:
    path:     /{id}/update
    defaults: { _controller: "IkasiBundle:Puesto:update" }
    methods:  [POST, PUT]

admin_puesto_delete:
    path:     /{id}/delete
    defaults: { _controller: "IkasiBundle:Puesto:delete" }
    methods:  [POST, DELETE]
