imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    ide: "phpstorm://open?file=%%f&line=%%1"
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator:     ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']
        # resources: ['bootstrap_3_horizontal_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ IkasiBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.7.jar
            apply_to: \.css
        yui_js:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.7.jar
            apply_to: \.js
        jpegoptim:
            bin: /usr/local/Cellar/jpegoptim
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
    assets:
        backend_css:
            inputs:
                - '@IkasiBundle/Resources/public/css/backend/style.css'
        frontend_css:
            inputs:
                - '@IkasiBundle/Resources/public/css/frontend/mystyle.css'
        backend_js:
            inputs:
                - '@IkasiBundle/Resources/public/js/backend/myscripts.js'
        frontend_js:
            inputs:
                - '@IkasiBundle/Resources/public/js/myscript.js'

braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    # jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
    jquery_path: @IkasiBundle/Resources/public/js/jquery/jquery-1.10.2.js
    less_filter: less # "less", "lessphp", "sass" or "none"
    fonts_dir: %kernel.root_dir%/../web/fonts
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Ikerib\IkasiBundle\Entity\User
    # profile:
    #     form:
    #         type: ikerib_user_profile

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        question_image:
            uri_prefix:         /uploads
            upload_destination: %kernel.root_dir%/../web/uploads

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

liip_imagine:
    resolvers:
       default:
            web_path: ~
#                web_root: %kernel.root_dir%/../web/uploads


    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [171, 180], mode: outbound }