user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

frontend:
    resource: "@IkasiBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

api:
    resource: "@IkasiBundle/Resources/config/routing/api.yml"
    prefix:   /api