# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  login_listener:
    class: Ikerib\IkasiBundle\Listener\LoginListener
    arguments: [ @router, @security.context, @doctrine ]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }